version: '2.1'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    # build: .
    volumes:
      - ./conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./gesad-plugin:/var/www/html/wp-content/plugins/my-plugin
      - ./gesad-theme:/var/www/html/wp-content/themes/my-theme
      - ./.wp-app/wp-content:/var/www/html/wp-content

    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_NAME: wordpress-database
      WORDPRESS_DB_USER: wordpress-username
      WORDPRESS_DB_PASSWORD: wordpress-password
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    ports:
      - 8070:80
    networks:
      - back
  mysqldb:
    image: mysql:5.7
    # container_name: 
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: wordpress-root
      MYSQL_DATABASE: wordpress-database
      MYSQL_USER: wordpress-username
      MYSQL_PASSWORD: wordpress-password
      MYSQL_ROOT_PASSWORD: wordpress-root
    networks:
      - back
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: 
      PMA_PORT: 3306
    networks:
      - back
networks:
  back:
volumes:
  db_data:
