version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: marcosdavy/mywordpress
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./gesad-theme:/usr/src/wordpress/wp-content/themes/gesad-theme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: root
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:8081
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - back
networks:
  back:
volumes:
  db_data: {}